2023-05-16 15:00:38,104 INFO Watching for file changes with StatReloader
2023-05-16 15:02:28,069 INFO Watching for file changes with StatReloader
2023-05-16 15:03:19,390 ERROR Internal Server Error: /accounts/signup/
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\News_Portal\venv\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\User\PycharmProjects\News_Portal\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\PycharmProjects\News_Portal\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\User\PycharmProjects\News_Portal\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\User\PycharmProjects\News_Portal\venv\lib\site-packages\allauth\decorators.py", line 20, in wrap
    resp = function(request, *args, **kwargs)
  File "C:\Users\User\PycharmProjects\News_Portal\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\User\PycharmProjects\News_Portal\venv\lib\site-packages\django\views\decorators\debug.py", line 92, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "C:\Users\User\PycharmProjects\News_Portal\venv\lib\site-packages\allauth\account\views.py", line 234, in dispatch
    return super(SignupView, self).dispatch(request, *args, **kwargs)
  File "C:\Users\User\PycharmProjects\News_Portal\venv\lib\site-packages\allauth\account\views.py", line 77, in dispatch
    response = super(RedirectAuthenticatedUserMixin, self).dispatch(
  File "C:\Users\User\PycharmProjects\News_Portal\venv\lib\site-packages\allauth\account\views.py", line 207, in dispatch
    return super(CloseableSignupMixin, self).dispatch(request, *args, **kwargs)
  File "C:\Users\User\PycharmProjects\News_Portal\venv\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\User\PycharmProjects\News_Portal\venv\lib\site-packages\allauth\account\views.py", line 105, in post
    response = self.form_valid(form)
  File "C:\Users\User\PycharmProjects\News_Portal\venv\lib\site-packages\allauth\account\views.py", line 248, in form_valid
    self.user = form.save(self.request)
  File "C:\Users\User\PycharmProjects\News_Portal\NewsPaper\accounts\models.py", line 25, in save
    common_group = Group.objects.get(name='common')
  File "C:\Users\User\PycharmProjects\News_Portal\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\User\PycharmProjects\News_Portal\venv\lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.Group.DoesNotExist: Group matching query does not exist.
2023-05-16 15:03:20,631 ERROR "POST /accounts/signup/ HTTP/1.1" 500 130365
2023-05-16 15:05:45,049 ERROR Internal Server Error: /upgrade/
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\News_Portal\venv\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\User\PycharmProjects\News_Portal\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\PycharmProjects\News_Portal\venv\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\User\PycharmProjects\News_Portal\NewsPaper\accounts\views.py", line 28, in upgrade_me
    authors_group = Group.objects.get(name='authors')
  File "C:\Users\User\PycharmProjects\News_Portal\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\User\PycharmProjects\News_Portal\venv\lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.Group.DoesNotExist: Group matching query does not exist.
2023-05-16 15:05:46,337 ERROR "GET /upgrade/ HTTP/1.1" 500 83996
2023-05-16 15:48:18,670 INFO C:\Users\User\PycharmProjects\News_Portal\NewsPaper\news_portal\models.py changed, reloading.
2023-05-16 15:48:20,171 INFO Watching for file changes with StatReloader
2023-05-16 15:49:15,154 INFO Watching for file changes with StatReloader
2023-05-16 15:54:56,664 INFO C:\Users\User\PycharmProjects\News_Portal\NewsPaper\NewsPaper\settings.py changed, reloading.
2023-05-16 15:55:00,117 INFO Watching for file changes with StatReloader
2023-05-16 15:56:51,137 INFO C:\Users\User\PycharmProjects\News_Portal\NewsPaper\NewsPaper\settings.py changed, reloading.
2023-05-16 16:22:41,538 INFO Watching for file changes with StatReloader
2023-05-16 16:23:33,425 INFO C:\Users\User\PycharmProjects\News_Portal\NewsPaper\NewsPaper\settings.py changed, reloading.
2023-05-16 16:23:34,779 INFO Watching for file changes with StatReloader
2023-05-16 16:24:01,120 INFO C:\Users\User\PycharmProjects\News_Portal\NewsPaper\NewsPaper\settings.py changed, reloading.
2023-05-16 16:24:02,439 INFO Watching for file changes with StatReloader
2023-05-16 16:24:49,443 INFO C:\Users\User\PycharmProjects\News_Portal\NewsPaper\NewsPaper\settings.py changed, reloading.
2023-05-16 16:24:50,818 INFO Watching for file changes with StatReloader
2023-05-16 16:26:12,189 INFO C:\Users\User\PycharmProjects\News_Portal\NewsPaper\NewsPaper\settings.py changed, reloading.
2023-05-16 16:26:13,607 INFO Watching for file changes with StatReloader
2023-05-16 16:26:24,666 INFO C:\Users\User\PycharmProjects\News_Portal\NewsPaper\NewsPaper\settings.py changed, reloading.
2023-05-16 16:26:26,207 INFO Watching for file changes with StatReloader
2023-05-16 16:26:38,279 INFO C:\Users\User\PycharmProjects\News_Portal\NewsPaper\NewsPaper\settings.py changed, reloading.
2023-05-16 16:26:39,517 INFO Watching for file changes with StatReloader
2023-05-16 16:27:43,551 INFO Watching for file changes with StatReloader
2023-05-16 16:28:03,687 INFO C:\Users\User\PycharmProjects\News_Portal\NewsPaper\NewsPaper\settings.py changed, reloading.
2023-05-16 16:28:05,225 INFO Watching for file changes with StatReloader
2023-05-16 16:28:18,294 INFO C:\Users\User\PycharmProjects\News_Portal\NewsPaper\NewsPaper\settings.py changed, reloading.
2023-05-16 16:28:54,810 INFO Watching for file changes with StatReloader
2023-05-17 15:17:15,971 INFO Watching for file changes with StatReloader
2023-05-17 15:17:26,095 ERROR Internal Server Error: /upgrade/
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\News_Portal\venv\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\User\PycharmProjects\News_Portal\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\PycharmProjects\News_Portal\venv\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\User\PycharmProjects\News_Portal\NewsPaper\accounts\views.py", line 28, in upgrade_me
    authors_group = Group.objects.get(name='authors')
  File "C:\Users\User\PycharmProjects\News_Portal\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\User\PycharmProjects\News_Portal\venv\lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.Group.DoesNotExist: Group matching query does not exist.
2023-05-17 15:17:28,219 ERROR "GET /upgrade/ HTTP/1.1" 500 80236
2023-05-17 15:17:49,387 ERROR Internal Server Error: /news/search/
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\News_Portal\venv\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\User\PycharmProjects\News_Portal\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\PycharmProjects\News_Portal\venv\lib\site-packages\django\views\generic\base.py", line 96, in view
    self = cls(**initkwargs)
  File "C:\Users\User\PycharmProjects\News_Portal\NewsPaper\news_portal\views.py", line 58, in __init__
    super().__init__(kwargs)
TypeError: __init__() takes 1 positional argument but 2 were given
2023-05-17 15:17:50,510 ERROR "GET /news/search/ HTTP/1.1" 500 71785
2023-05-17 15:31:52,263 INFO C:\Users\User\PycharmProjects\News_Portal\NewsPaper\news_portal\filters.py changed, reloading.
2023-05-17 15:31:54,618 INFO Watching for file changes with StatReloader
2023-05-17 16:16:59,221 INFO Watching for file changes with StatReloader
2023-05-17 16:17:18,944 ERROR Internal Server Error: /news/search/
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\News_Portal\venv\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\User\PycharmProjects\News_Portal\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\PycharmProjects\News_Portal\venv\lib\site-packages\django\views\generic\base.py", line 96, in view
    self = cls(**initkwargs)
  File "C:\Users\User\PycharmProjects\News_Portal\NewsPaper\news_portal\views.py", line 58, in __init__
    super().__init__(kwargs)
TypeError: __init__() takes 1 positional argument but 2 were given
2023-05-17 16:17:20,799 ERROR "GET /news/search/ HTTP/1.1" 500 71785
2023-05-17 16:26:39,069 INFO Watching for file changes with StatReloader
2023-05-17 16:41:17,201 INFO Watching for file changes with StatReloader
2023-05-17 16:49:13,079 INFO Watching for file changes with StatReloader
2023-05-17 16:56:16,937 INFO Watching for file changes with StatReloader
2023-05-17 17:01:14,068 INFO Watching for file changes with StatReloader
2023-05-17 17:20:39,874 INFO C:\Users\User\PycharmProjects\News_Portal\venv\Lib\site-packages\django\contrib\__init__.py changed, reloading.
2023-05-17 17:20:41,364 INFO Watching for file changes with StatReloader
